### ISSUE TITLE
Does not work when erc-insert-timestamp-function is set to erc-insert-timestamp-left

### ISSUE THREAD

**Issue by gausby** [thisirs/erc-colorize#2]
I seems to stop colorizing the messages if the timestamp is set to the left:

``` elisp
(setq erc-insert-timestamp-function 'erc-insert-timestamp-left)
```

**Comment by thisirs** [comment]
Thanks for reporting this, this should be okay now!

**Comment by gausby** [comment]
Thank you. I can't wait for this to hit melpa :+1: 

erc-colorize is really cool!
