### ISSUE TITLE
conflict with erc-track-mode?

### ISSUE THREAD

**Issue by xwl** [thisirs/erc-colorize#3]
It seems once erc-colorize is enabled, erc-track-mode won't show unread count info on mode line any more.  There seems two issues:
1. erc-find-parsed-property call in erc-colorize-message will somehow remove 'erc-parsed call.  And erc-track-mode is looking for it when counting unread messages, in function: erc-track-modified-channels.
2. Also in erc-colorize-message:
   
   (erc-put-text-property
        (point-min) (point-max)
        'face match-face))))

This will override any existing faces there.  Again, erc-track-mode also relies on them for counting.

I have some local fix, https://github.com/xwl/erc-colorize/commit/3dc4ccb36946bc1649a50699851f7cf2e985138e

**Comment by thisirs** [comment]
Hi,

thanks for looking into this! I actually don't use erc-track that much.
Just noticed that some faces were clobbered but I didn't bother...

Anyway, I haven't the time to fully test your patch at the moment but it
seems correct! Shouldn't we require erc-track somewhere in case someone
uses erc-colorize and not erc-track?

2015-12-27 18:07 GMT+01:00 William Xu notifications@github.com:

**Comment by xwl** [comment]
There was a mistake in my changes.  Actually there is no need to change erc-track-\* variables.  Anyhow, i'm simply keeping the original faces there.  Updated patch: https://github.com/xwl/erc-colorize/commit/ed0b71efc27cd5dc8be8ef79e5247ac67839d8dc

**Comment by thisirs** [comment]
I think there is already some code in `erc-button` that solves this... Look at `erc-button-add-face` in `erc-button.el`... It seems to work ok with both `erc-colorize` and `erc-match` enabled! I'll push a fix if you don't beat me to it ;)

**Comment by xwl** [comment]
Sure, as long as it works.. :)

**Comment by xwl** [comment]
The fix with erc-button is much more clean, thanks.

It is actually pity that elisp doesn't have this functionality as builtin.
